name: Node.js CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check Node & npm version
        run: |
          node --version
          npm --version

      - name: Create a test file and run it
        run: |
          echo "console.log('Hello from Node.js inside GitHub Actions!')" > app.js
          node app.js